### ISSUE TITLE
关于tileset空间范围框和矩阵变换的计算

### ISSUE THREAD

**Issue by yueyan-zm** [scially/Cesium3DTilesConverter#14]
大佬，您好！
我是一个搞gis的，前不久因为工作的需要，我想要将shp转化为三维，所以就有幸看到了您的这个项目。我用了一些时间，用rust重写了shp转b3dm的功能，但是因为完全是照抄，中间有些计算公式（空间范围框其实还好理解，但是矩阵transform的计算我不知道是怎样的）我还不是很了解，方便指教一下吗？

**Comment by scially** [comment]
什么问题呢？

**Comment by yueyan-zm** [comment]
就是关于transfrom的这即个值是怎么计算出来的，有什么计算公式吗，为什么要引入那么大elliposed的三个值，因为我引入的向量库他默认是单精度浮点型的数，后面这里要算向量的模的时候，已经溢出了，最后在这里转换为了双精度浮点型，但是感觉好像丢失了精度。

**Comment by scially** [comment]
就是模型中心点你假设是0,0,0，cesium用transform表示真实位置，transform是从模型0,0,0到其真实位置（xyz）的转换矩阵，xyz和blh之间的转换需要椭球参数。

**Comment by yueyan-zm** [comment]
好的，知道了，谢谢大佬

**Comment by yueyan-zm** [comment]
好的，知道了，谢谢大佬
