### ISSUE TITLE
osgb转3dtiles坐标还有点偏移

### ISSUE THREAD

**Issue by yipiaojun** [scially/Cesium3DTilesConverter#17]
用cesium3DTilesConverter 2.1版测试osgb转3dtiles，与cesiumlab转的效果对比，坐标还是有显著的偏移。(cesium3DTilesConverter 2.1和原来的 "3dtiles"工具的偏移效果是一样的。)

<img width="359" alt="3dtiles对比-cesiumlab(1)" src="https://user-images.githubusercontent.com/15865996/218252233-20f01c7b-6854-40ff-9c4a-bf8cfc79c8b0.png">

<img width="292" alt="3dtiles对比-cesium3DConverter(1)" src="https://user-images.githubusercontent.com/15865996/218252236-8d1e24fe-3e3b-4bc1-9b65-bde2efef9dd2.png">

**Comment by yipiaojun** [comment]
fanvanzh 说 ”这个可能需要逐顶点对osgb进行proj4投影，现在是只处理了局部坐标系的原点。“
https://github.com/fanvanzh/3dtiles/issues/209

**Comment by 472818652** [comment]
fixed by https://github.com/fanvanzh/3dtiles/pull/249
fanvanzh那边已经修复了，这边有计划把修复同步过来吗

**Comment by scially** [comment]
是的，正在同步
