### ISSUE TITLE
fork了后，做了修改，是一个不依赖QT的版本，能否开源出来？

### ISSUE THREAD

**Issue by xrui94** [scially/Cesium3DTilesConverter#28]
我fork了一个你的这个项目，然后改成了不依赖QT的C++17版本，想问下我可以开源出来么？或者，能否新建一个 no_QT的分支，我来提交并维护。我打算再增加一些其它的转换功能。

**Comment by scially** [comment]
可以，有新的想法也欢迎提交PR
