### ISSUE TITLE
Could NOT find GDAL (missing: GDAL_LIBRARY GDAL_INCLUDE_DIR)

### ISSUE THREAD

**Issue by CHCDST-SY** [scially/Cesium3DTilesConverter#3]
cmake时提示这个，是需要把编译好的gdal库添加到win的环境变量里面吗？

**Comment by scially** [comment]
你是怎么编译的 需要指定下gdal的Cmake位置

**Comment by scially** [comment]
如果是windows，建议直接用vcpkg安装

**Comment by CHCDST-SY** [comment]
> 如果是windows，建议直接用vcpkg安装

我是用vs2017直接打开的cmakelist.txt，然后自动编译运行，报的这个错

**Comment by scially** [comment]
gdal装了没

**Comment by CHCDST-SY** [comment]
> gdal装了没

vcpkg装gdal报错了，然后我自己编译了一个gdal版本，但是没有放到环境变量里面

**Comment by scially** [comment]
那我先关闭问题。
