### ISSUE TITLE
顶层重建的一点疑惑

### ISSUE THREAD

**Issue by cici19850** [scially/Cesium3DTilesConverter#30]
你好，我用代码里面的测试数据测试了顶层重建的功能，有几个问题没有理解呢：
1、转换后的b3dm为什么只保留范围相同的的最清晰的tile，其余的不要了呢？比如Tile_+000_+012下，实际生成的Tile_+000_+012.b3dm是Tile_+000_+012_L18_0uuuu.osgb的数据，15、16、17是因为范围相同，所以不要了吗？
2、顶层合并后，top下面的所有.b3dm文件，都只是读取了根的osgb（Tile_+000_+012.osgb、Tile_+000_+013.osgb、Tile_+000_+014.osgb、Tile_+000_+015.osgb、Tile_+000_+016.osgb、Tile_+000_+017.osgb）作为group节点里面的node， 15、16、17这些osgb也没有读取，这是为什么呢？

**Comment by scially** [comment]
1. 是我有一个geometricError做控制，太粗糙的就不考虑了。 那根据计算规则到了18级而已。
2. 是因为我在做合并根节点的时候，本身就是要对纹理和顶点压缩，所以直接拿跟节点往上重建（这里也是我自己想出来的策略，不知道实际使用中应该怎么考虑）

**Comment by scially** [comment]
看着相同，其实vertex用OSG Sample做了优化的（只是不多），在最新的代码中给了优化，重建顶层后，对top的osg进行geometricError筛选，会避免这个情况
