### ISSUE TITLE
大数据转化,find a geode not in PagedLOD中途截断

### ISSUE THREAD

**Issue by sxyws** [scially/Cesium3DTilesConverter#32]
在最新版本中,处理大型数据时执行到一半就会中途取消
![微信图片_20231226102712](https://github.com/scially/Cesium3DTilesConverter/assets/126746985/d250437c-8768-4d39-a042-095a92bb84bf)
(处理数据有10Gb)
但是在上一版本处理是没有问题的
![微信图片_20231226102736](https://github.com/scially/Cesium3DTilesConverter/assets/126746985/04602fe1-4b3d-41ba-8d64-f537adf65ff3)

**Comment by sxyws** [comment]
小型数据转化没有问题

**Comment by mofei031026** [comment]
我用两个瓦块测试都报这个错误了

**Comment by scially** [comment]
我这里测试了下，没有问题，你是用的最新版吗 3.1.1这个？

**Comment by sxyws** [comment]
是的,我用的就是3.1.1的版本,使用3.1.0的版本是没有问题的,就是要修改xml文件

**Comment by sxyws** [comment]
是的,我使用的是3.1.1版本的,会自动结束任务.我使用小数据测试是没有问题的,大数据量测试就会出现这种问题

**Comment by sxyws** [comment]
我查看了一下在执行Warning: find a geode not in PagedLOD (:0, )时,占满了全部的内存,导致任务的崩溃]
