### ISSUE TITLE
如何解析b3dm文件

### ISSUE THREAD

**Issue by wangdemon** [scially/Cesium3DTilesConverter#4]
将osgb文件转为b3dm后，那b3dm文件该如何解析？有没有b3dm解析的相关的c++库？

**Comment by wangdemon** [comment]
或者说，能不能将b3dm转为glTF 2.0版本的glb文件

**Comment by scially** [comment]
你好，参考这个类：https://github.com/scially/Cesium3DTilesConverter/blob/master/include/OSGBConvert.h#L28
