### ISSUE TITLE
请问作者如何实现shape数据转3dtiles box模式

### ISSUE THREAD

**Issue by fireforydh** [scially/Cesium3DTilesConverter#8]
前作fanvanzh将shape数据转3dtiles格式数据中，是创建建筑物模型的region范围框（tileset.json中的region矩阵），请问如何实现box范围框（类似于osgb转换后的tileset.json中的box矩阵），十分感谢，指导一二！！！

**Comment by scially** [comment]
参考[项目这里代码](https://github.com/scially/Cesium3DTilesConverter/blob/master/src/ShpConvert.cpp#:~:text=All%20Geometry%20Envelope-,%7B,double%20boxHeight%20%3D%20(nodeBox.MaxY%20%2D%20nodeBox.MinY)%3B,-double%20maxHeight%20%3D%200)，对于3dtiles的[region](https://github.com/CesiumGS/3d-tiles/tree/main/specification#region)要求的就是经纬度（弧度）

**Comment by fireforydh** [comment]
哥，这个是region的实现，box的实现有参考吗？

**Comment by scially** [comment]
[region](https://github.com/CesiumGS/3d-tiles/tree/main/specification#region)和[box](https://github.com/CesiumGS/3d-tiles/tree/main/specification#box) 最大的不同在于是否有地理信息，在不考虑这点的情况下是可以互相转换的，参考[这里代码](https://github.com/scially/Cesium3DTilesConverter/blob/master/include/BoundingVolumeBox.h#:~:text=/summary%3E-,class%20BoundingVolumeBox%20%3A%20public%20BaseObject%20%7B,%7D,-virtual%20QJsonValue%20write)，然后通过经纬度给box一个定位，可以转为region，参考[这里代码](https://github.com/scially/Cesium3DTilesConverter/blob/master/src/BoundingVolumeRegion.cpp#:~:text=BoundingVolumeRegion%20BoundingVolumeRegion%3A%3AtoRadin,%7D)
